### ISSUE TITLE
assignment 4 Reversing string

### ISSUE THREAD

**Issue by 56bit23** [vtcbca/basic-programming-57bit23#2]
What is string?

**Comment by 57bit23** [comment]
String is a group of character

**Comment by 56bit23** [comment]
How to initialise a string?

**Comment by 57bit23** [comment]
In Python, a string is a sequence of characters enclosed in single quotes (' ').

**Comment by 57bit23** [comment]
What is the main purpose to use string in python?

**Comment by 56bit23** [comment]
What is the main purpose to use string in python?

**Comment by 57bit23** [comment]
the main purpose to use string is to represent textual data.

**Comment by 56bit23** [comment]
Can strings contain alphanumeric value?

**Comment by 57bit23** [comment]
Yes, strings can contain alphanumeric values.
Letters (A-Z, a-z)
Numbers (0-9)
Special characters (e.g., @, #, !, etc.), if needed

**Comment by 56bit23** [comment]
Thank you @57bit23 for your response.

**Comment by 57bit23** [comment]
@56bit23 You welcome
