### ISSUE TITLE
Assignment 3- Fibonacci Sequence Generator

### ISSUE THREAD

**Issue by 45bit23** [vtcbca/basic-programming-57bit23#3]
What is  Fibonacci Sequence Generator?

**Comment by 57bit23** [comment]
The Fibonacci sequence is a series of numbers in which each number is the sum of the two preceding ones, typically starting with 0 and 1.

**Comment by 45bit23** [comment]
How do you calculate a number in the Fibonacci sequence?

**Comment by 57bit23** [comment]
Fibonacci Sequence is a series of numbers in which each number, starting with 0 and 1, is generated by adding the two preceding numbers. It forms the sequence of 0, 1, 1, 2, 3, 5, 8, 13, 21,… Each number in the Fibonacci series is the sum of the two numbers before it.

**Comment by 45bit23** [comment]
What are the Fibonacci sequence rules?

**Comment by 57bit23** [comment]
The Fibonacci Sequence can be written as a "Rule" (see Sequences and Series). First, the terms are numbered from 0 onwards like this: So term number 6 is called x6(which equals 8). So we can write the rule: The Rule is xn = xn−1 + xn−2 where: 1. xnis term number "n" 2. xn−1is the previous term (n−1) 3. xn−2is the term before that (n−2).

**Comment by 45bit23** [comment]
What are the first 15 numbers in the Fibonacci sequence?

**Comment by 57bit23** [comment]
0,1,1,2,3,5,8,13,21,34,55,89,144,233,377.

**Comment by 45bit23** [comment]
How to find Fibonacci terms based on a starting number?

**Comment by 57bit23** [comment]
Add the index n value to find the Fibonacci terms based on a starting number or the number of terms in the sequence.

**Comment by 45bit23** [comment]
I get it thank you
