### ISSUE TITLE
Assignment - 5: Check if a string is a palindrome or not

### ISSUE THREAD

**Issue by 54bit23** [vtcbca/basic-programming-57bit23#5]
What is the simplest example of a palindrome?

**Comment by 57bit23** [comment]
The simplest example is "a", a single character.

**Comment by 54bit23** [comment]
How do you reverse a string in Python to check for palindromes?

**Comment by 57bit23** [comment]
Use slicing:

`reversed_string = string[::-1]`

**Comment by 54bit23** [comment]
Is an empty string considered a palindrome?

**Comment by 57bit23** [comment]
Yes, because it reads the same backward and forward.

**Comment by 54bit23** [comment]
Can a palindrome contain spaces?

**Comment by 57bit23** [comment]
Yes, but you may need to remove spaces for proper checking.

**Comment by 54bit23** [comment]
How do you make the palindrome check case-insensitive?

**Comment by 57bit23** [comment]
Convert the string to lowercase using the lower() method:

`string = string.lower()`

**Comment by 54bit23** [comment]
thanks @57bit23
