### ISSUE TITLE
Assignment-8 : Pattern of Alphabets  

### ISSUE THREAD

**Issue by 51bit23** [vtcbca/basic-programming-57bit23#6]
What does the program do?

**Comment by 57bit23** [comment]
It prints a pattern of alphabets in a triangle format with spaces for alignment.

**Comment by 51bit23** [comment]
What is the input required for the program?

**Comment by 57bit23** [comment]
It adds spaces at the beginning of each row to align the pattern.

**Comment by 51bit23** [comment]
Can you tell me What will the program print if n = 1?

**Comment by 57bit23** [comment]
Simple It will print:


`A`

**Comment by 51bit23** [comment]
What happens if the input is 0?

**Comment by 57bit23** [comment]
The program will not print anything since no rows need to be displayed.

**Comment by 51bit23** [comment]
Can this program handle lowercase letters?

**Comment by 51bit23** [comment]
Yes, Just  by modifying the ASCII base from (uppercase) to (lowercase).

**Comment by 57bit23** [comment]
Yes, Just by modifying the ASCII base from (uppercase) to (lowercase).
